# Generated by Django 5.0 on 2023-12-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0002_alter_keyword_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichedtransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='enrichedtransaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='enrichedtransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='enrichedtransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrichment.transaction'),
        ),
        migrations.AlterField(
            model_name='enrichedtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrichment.category'),
        ),
        migrations.AlterField(
            model_name='enrichedtransaction',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrichment.keyword'),
        ),
        migrations.AlterField(
            model_name='enrichedtransaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrichment.merchant'),
        ),
    ]
